import {
  Assignment,
  AssignmentSubmission,
  Attendance,
  AuditLog,
  AdmissionApplication,
  Batch,
  Certificate,
  ClassSchedule,
  Course,
  CourseCategory,
  CourseModule,
  CourseResource,
  Enrollment,
  FeePlan,
  Instructor,
  Invoice,
  Lead,
  Offer,
  Lesson,
  Notification,
  Payment,
  PaymentIntent,
  ReferralCode,
  ReferralRedemption,
  ScholarshipTest,
  Setting,
  StudentProfile,
  StudentWallet,
  User,
  WalletLedger,
} from './academy.entities';
import { BlogPost } from './blog-post.entity';

export * from './academy.entities';
export * from './blog-post.entity';

export const academyEntities = [
  User,
  StudentProfile,
  StudentWallet,
  CourseCategory,
  Course,
  CourseModule,
  CourseResource,
  Lesson,
  Instructor,
  Batch,
  Enrollment,
  ClassSchedule,
  Attendance,
  Assignment,
  AssignmentSubmission,
  FeePlan,
  Payment,
  PaymentIntent,
  Invoice,
  Certificate,
  Lead,
  AdmissionApplication,
  ReferralCode,
  ReferralRedemption,
  WalletLedger,
  ScholarshipTest,
  Offer,
  Notification,
  Setting,
  AuditLog,
  BlogPost,
];
